ProtoFolderPath: Resources/Text/Proto
LanguageFolderPath: Resources/Text/Language
ConfigFolderPath: Resources/Text/Config
UIPrefabPath: Resources/Prefab/UI
FXPrefabPath: Resources/Prefab/FX

IsLocalResource: true
IsLocalSave: true

UseHeadUpDisplay: true
